{{ if ne .Values.environment "ci" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
{{ toYaml .Values.prometheusRules.labels | indent 4 }}
  name: {{ .Release.Name }}
spec:
  groups:
  - name: {{ .Release.Name }}.rules
    rules:
    - alert: TransactionSent
      annotations:
        message: 'New transaction sent from account {{`{{ $labels.sender_name }}`}}, check https://polkascan.io/pre/{{ .Values.networkId }}/account/{{`{{ $labels.sender_address }}`}}#transactions for details'
      expr: increase(polkadot_account_transaction_total[2m]) > 0
      for: 30s
      labels:
        severity: info
{{ end }}
