apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels:
    app: {{ include "app.name" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ include "app.name" . }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        args:
        - -c
        - /app/config/main.yaml
        ports:
        - name: metrics
          containerPort: {{ .Values.config.port }}
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.config.port }}
          initialDelaySeconds: 10
          timeoutSeconds: 200
        {{ if ne .Values.config.environment "ci" }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{ end }}
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: {{ include "app.name" . }}
