{{ if ne .Values.environment "ci" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: polkadot-watcher
  labels:
{{ toYaml .Values.serviceMonitor.labels | indent 4 }}
spec:
  selector:
    matchLabels:
      app: polkadot-watcher
  endpoints:
  - port: metrics
{{ end }}
