environment: production
port: 3000

image:
  repo: web3f/polkadot-watcher
  tag: latest

config:
  endpoint: "wss://cc3-3.kusama.network"
  port: 3000
  logLevel: info
  subscribe:
    transactions: []
    producers: []

serviceMonitor:
  labels:
    group: w3f
    release: prometheus-operator

prometheusRules:
  labels:
    app: w3f

networkId: kusama

origin: cluster

## EXAMPLE:
##   resources:
##     requests:
##       cpu: "1000m"
##       memory: "2Gi"
##
resources: 
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "300m"
    memory: "500Mi" 
