environment: production
port: 3000

image:
  repo: web3f/polkadot-watcher
  tag: v2.1.0

config:
  endpoint: "wss://kusama-rpc.polkadot.io"
  port: 3000
  logLevel: info
  validators: []

serviceMonitor:
  labels:
    group: w3f
    release: prometheus-operator

prometheusRules:
  labels:
    app: w3f

networkId: kusama

origin: cluster

resources:
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "100m"
    memory: "500Mi"
