environment: production
port: 3000

image:
  repo: web3f/polkadot-watcher
  tag: v3.2.2

config:
  endpoint: "wss://kusama-rpc.polkadot.io"
  port: 3000
  logLevel: info
  validators: []

serviceMonitor:
  enabled: true #to be enabled for each instance
  labels:
    group: w3f
    release: prometheus-operator

prometheusRules:
  enabled: false #if you have multiple instances, enabled it just once to avoid duplicated alerts
  labels:
    app: w3f
  origin: cluster  
  heartbeat: true  

resources:
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "100m"
    memory: "500Mi"
