environment: production
port: 3000
namespace: default
image:
  repo: web3f/polkadot-watcher
  tag: latest

config:
  endpoint: "wss://cc3-3.kusama.network"
  port: 3000
  logLevel: info
  subscribe:
    transactions: []
    producers: []

serviceMonitor:
  labels:
    group: w3f
    release: prometheus-operator

prometheusRules:
  labels:
    app: w3f

networkId: kusama
